from url import video_id
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import TranscriptsDisabled
import sys
import os

import warnings

# Filter out warning messages generated by the youtube_transcript_api library
warnings.filterwarnings("ignore", category=UserWarning, module='youtube_transcript_api')

# Call the get_transcript method
data = YouTubeTranscriptApi.get_transcript(video_id)


# try:
#     data = YouTubeTranscriptApi.get_transcript(video_id)
# except TranscriptsDisabled as e:
#     print("Error getting transcript for video")
#     print(e)

transcript = ""
for d in data:
    transcript += d['text'] + " "

# for element in data:
#     print(element['text'])